enum CLIENT {
  CREATE_ROOM = "CREATE_ROOM",
  SEND_ROOM_MESSAGE = "SEND_ROOM_MESSAGE",
  JOIN_ROOM = "JOIN_ROOM",
}

enum SERVER {
  ROOMS = "ROOM",
  JOINED_ROOM = "JOINED_ROOM",
  ROOM_MESSAGE = "ROOM_MESSAGE",
}

const EVENTS = {
  CONNECTION: "connection",
  CLIENT,
  SERVER,
};

export default EVENTS;
